name: Deploy Playwright Reports

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-reports:
    name: Deploy HTML Reports
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright
      run: npx playwright install chromium
    
    - name: Create .env file
      run: |
        echo "SAUCEDEMO_BASE_URL=${{ secrets.SAUCEDEMO_BASE_URL }}" >> .env
        echo "SAUCEDEMO_USERNAME=${{ secrets.SAUCEDEMO_USERNAME }}" >> .env
        echo "SAUCEDEMO_PASSWORD=${{ secrets.SAUCEDEMO_PASSWORD }}" >> .env
        echo "AIRPORTGAP_BASE_URL=${{ secrets.AIRPORTGAP_BASE_URL }}" >> .env
    
    - name: Run Playwright tests
      run: npm test
    
    - name: Prepare reports for deployment
      run: |
        # Copy the generated HTML report to public directory
        mkdir -p public
        cp -r playwright-report/* public/ || echo "No playwright-report directory found"
        
        # Ensure we have an index.html
        if [ ! -f "public/index.html" ]; then
          echo "<h1>No test reports generated</h1>" > public/index.html
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4